export const GRADES = ["R", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"];

export const SA_SUBJECTS = [
  "Mathematics",
  "Mathematical Literacy",
  "Physical Sciences",
  "Life Sciences",
  "Natural Sciences",
  "Geography",
  "History",
  "English Home Language",
  "English First Additional Language",
  "Afrikaans Home Language",
  "Afrikaans First Additional Language",
  "isiZulu Home Language",
  "isiXhosa Home Language",
  "Sesotho Home Language",
  "Setswana Home Language",
  "Sepedi Home Language",
  "Tshivenda Home Language",
  "Xitsonga Home Language",
  "Life Orientation",
  "Accounting",
  "Business Studies",
  "Economics",
  "Computer Applications Technology",
  "Information Technology",
  "Visual Arts",
  "Music",
  "Dance Studies",
  "Dramatic Arts",
  "Engineering Graphics and Design",
  "Consumer Studies",
  "Hospitality Studies",
  "Tourism",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Civil Technology",
  "Electrical Technology",
  "Mechanical Technology",
  "Religion Studies",
  "Creative Arts",
  "Social Sciences",
  "Economic and Management Sciences",
  "Technology",
  "English",
  "Afrikaans",
  "isiZulu",
  "isiXhosa",
  "Mathematics (GET)",
];

export const PROVINCES = [
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];

export const DAYS_OF_WEEK = [
  { value: 1, label: "Monday" },
  { value: 2, label: "Tuesday" },
  { value: 3, label: "Wednesday" },
  { value: 4, label: "Thursday" },
  { value: 5, label: "Friday" },
];

export const REWARD_CATEGORIES = [
  { value: "academic", label: "Academic Excellence", color: "bg-blue-100 text-blue-700" },
  { value: "behavior", label: "Good Behaviour", color: "bg-green-100 text-green-700" },
  { value: "attendance", label: "Perfect Attendance", color: "bg-amber-100 text-amber-700" },
  { value: "participation", label: "Active Participation", color: "bg-purple-100 text-purple-700" },
  { value: "leadership", label: "Leadership", color: "bg-red-100 text-red-700" },
  { value: "improvement", label: "Most Improved", color: "bg-teal-100 text-teal-700" },
  { value: "other", label: "Other", color: "bg-gray-100 text-gray-700" },
];

export const BADGE_EMOJIS: Record<string, string> = {
  star: "⭐",
  trophy: "🏆",
  medal: "🥇",
  book: "📚",
  lightbulb: "💡",
  rocket: "🚀",
  heart: "❤️",
  shield: "🛡️",
};
