export function downloadAsWord(filename: string, title: string, content: string) {
  const html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/1999/xhtml'>
    <head>
      <meta charset='utf-8'>
      <title>${title}</title>
      <style>
        body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #333; }
        h1 { font-size: 18pt; color: #0F3D3E; margin-bottom: 12pt; border-bottom: 2pt solid #D4A843; padding-bottom: 6pt; }
        h2 { font-size: 14pt; color: #1A5F5F; margin-top: 18pt; margin-bottom: 6pt; }
        h3 { font-size: 12pt; color: #2D8A8A; margin-top: 12pt; margin-bottom: 6pt; }
        p { margin-bottom: 8pt; }
        ul { margin-bottom: 8pt; }
        li { margin-bottom: 4pt; }
        table { width: 100%; border-collapse: collapse; margin: 12pt 0; }
        th, td { border: 1pt solid #ccc; padding: 6pt; text-align: left; }
        th { background: #E6F5F4; color: #0F3D3E; }
        .footer { margin-top: 24pt; font-size: 9pt; color: #666; border-top: 1pt solid #ccc; padding-top: 6pt; }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        Generated by EduPlan SA — South African Education Platform
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', html], {
    type: 'application/msword',
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.doc') ? filename : `${filename}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
