export function downloadAsWord(filename: string, title: string, content: string) {
  const html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/1999/xhtml'>
    <head>
      <meta charset='utf-8'>
      <title>${title}</title>
      <style>
        body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #333; }
        h1 { font-size: 18pt; color: #0F3D3E; margin-bottom: 12pt; border-bottom: 2pt solid #D4A843; padding-bottom: 6pt; }
        h2 { font-size: 14pt; color: #1A5F5F; margin-top: 18pt; margin-bottom: 6pt; }
        h3 { font-size: 12pt; color: #2D8A8A; margin-top: 12pt; margin-bottom: 6pt; }
        p { margin-bottom: 8pt; }
        ul { margin-bottom: 8pt; }
        li { margin-bottom: 4pt; }
        table { width: 100%; border-collapse: collapse; margin: 12pt 0; }
        th, td { border: 1pt solid #ccc; padding: 6pt; text-align: left; }
        th { background: #E6F5F4; color: #0F3D3E; }
        .footer { margin-top: 24pt; font-size: 9pt; color: #666; border-top: 1pt solid #ccc; padding-top: 6pt; }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        Generated by EduPlan SA — South African Education Platform
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', html], {
    type: 'application/msword',
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.doc') ? filename : `${filename}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Convert markdown-like text to clean HTML for Word docs */
export function markdownToHtml(text: string): string {
  let html = text
    // Code blocks
    .replace(/```[\s\S]*?```/g, (match) => {
      const code = match.replace(/```/g, '').trim();
      return `<pre style="background:#f5f5f5;padding:8pt;border:1pt solid #ddd;font-family:Consolas,monospace;font-size:10pt;">${code}</pre>`;
    })
    // Headings
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code style="background:#f5f5f5;padding:2pt 4pt;font-family:Consolas,monospace;font-size:10pt;">$1</code>')
    // Unordered lists
    .replace(/^\s*[-•] (.*$)/gim, '<li>$1</li>')
    // Ordered lists
    .replace(/^\s*\d+\.\s+(.*$)/gim, '<li>$1</li>')
    // Checkboxes
    .replace(/^\s*- \[ \] (.*$)/gim, '<li>☐ $1</li>')
    .replace(/^\s*- \[x\] (.*$)/gim, '<li>☑ $1</li>')
    // Tables (simple markdown tables)
    .replace(/\|([^|]*)\|([^|]*)\|/g, (match, c1, c2) => {
      return `<td>${c1.trim()}</td><td>${c2.trim()}</td>`;
    })
    // Line breaks
    .replace(/\n/g, '<br>');

  // Wrap consecutive <li> elements in <ul>
  html = html.replace(/(<li>.*?<\/li>)+/g, (match) => `<ul>${match}</ul>`);

  return html;
}

/** Strip markdown to plain text (for previews and clean generation) */
export function stripMarkdown(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, '')
    .replace(/^### /gim, '')
    .replace(/^## /gim, '')
    .replace(/^# /gim, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^\s*[-•] /gim, '')
    .replace(/^\s*\d+\.\s+/gim, '')
    .replace(/^\s*- \[([ x])\] /gim, '')
    .replace(/\|/g, '')
    .trim();
}
